- name: Prepare Proxmox autoinstall environment
  hosts: localhost
  vars:
    storage_base_dir: /tmp
    proxmox_iso_url: https://enterprise.proxmox.com/iso/proxmox-ve_8.2-1.iso
    proxmox_iso_sha256: d99d182a0df4ba94c27668d3e33d14cc286d775a7bdf571a86c24ea522009e93
  tasks:
    - name: Create storage directories
      ansible.builtin.file:
        path: "{{ item }}"
      loop:
        - "{{ storage_base_dir }}/config/answers"
        - "{{ storage_base_dir }}/iso"
    - name: Download Proxmox ISO
      ansible.builtin.get_url:
        url: "{{ proxmox_iso_url }}"
        dest: "{{ storage_base_dir }}/iso"
        mode: u=rw,go=r
        checksum: "sha256:{{ proxmox_iso_sha256 }}"
    - name: Create autoinstall server container
      community.docker.docker_container:
        name: proxmox-autoinstall-server
        image: ghcr.io/somanydoors/proxmox-autoinstall-server
        state: present
        detached: true
        ports:
          - 8000
        volumes:
          - "{{ storage_base_dir }}/config:/config"
    - name: Create autoinstall ISO
      community.docker.docker_container:
        name: proxmox-autoinstall-iso-builder
        image: ghcr.io/somanydoors/proxmox-autoinstall-iso-builder
        state: present
        auto_remove: true
        cleanup: true
        detached: false
        command:
          - "prepare-iso"
          - "/iso/proxmox-ve_8.2-1.iso"
          - "--fetch-from http"
          - "--url http://{{ ansible_host_ip }}/answer"
          - "--output /iso/proxmox-ve_8.2-1-autoinstall.iso"
        volumes:
          - "{{ storage_base_dir }}/iso:/iso"
